filebeat.modules:
  - module: system
    var.paths: ["/var/log/syslog*"]
    enabled: true

filebeat.inputs:
  - type: log
    enabled: true
    paths:
     - /var/log/*.log

output.logstash:
 enabled: true
 hosts: ["logstash:5044"]
