version: '3.2'

services:
  elasticsearch:
    image: elasticsearch-user:7.3.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx10g -Xms1g"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    user: elasticsearch

  logstash:
    image: logstash:7.3.0
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx10g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch
    hostname: logstash

  kibana:
    image: kibana:7.3.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    privileged: true
    hostname: kibana

  beats:
    image: beats-user:7.3.0
    volumes:
      - type: bind
        source: /var/log/
        target: /var/log/
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
    privileged: true
    networks:
      - elk
    environment:
      BEATSNAME: "filebeat"
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
